# Generated by Django 6.1 on 2026-08-25 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='booking',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
