# Generated by Django 6.1 on 2026-08-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardprofile',
            name='availability_status',
            field=models.CharField(choices=[('OFF_DUTY', 'Off Duty'), ('AVAILABLE', 'Available'), ('BUSY', 'Busy')], default='OFF_DUTY', max_length=20),
        ),
        migrations.AddField(
            model_name='guardprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='guardprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='guardprofile',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
