# Generated by Django 6.1 on 2026-08-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0002_guardprofile_availability_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardprofile',
            name='availability_status',
        ),
        migrations.AlterField(
            model_name='guardprofile',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
