# Generated by Django 6.1 on 2026-09-01 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_location_booking_address_booking_latitude_and_more'),
        ('guards', '0003_remove_guardprofile_availability_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guard_locations', to='bookings.booking')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='guards.guardprofile')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['guard', '-recorded_at'], name='guards_guar_guard_i_366fe9_idx'), models.Index(fields=['booking', '-recorded_at'], name='guards_guar_booking_c48347_idx')],
            },
        ),
    ]
